// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfvrhnvtqchvcjedmkvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmdnJobnZ0cWNodmNqZWRta3ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjY4NzcsImV4cCI6MjA1NzgwMjg3N30.AevlEdRcdMgSgN3dDdCZPBfdaOPD4qK9b0lM-EVZ8oA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);